version: '3.8'

services:
  web:
    build: .
    ports:
      - "5004:5004"
    environment:
      - SPREADSHEET_ID=1Yh5ZBrxSN8Tg7zxBbjU-w-pIoFxQhvdgRNGzEHfqUzM
    volumes:
      - ./churches_data.json:/app/churches_data.json
      - ./service-account.json:/app/service-account.json
    restart: unless-stopped
